org.gradle.jvmargs=-Xmx1536M -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradel.daemon=true
org.gradel.parallel=false
org.gradel.configureondemand=true
org.gradle.caching=true
org.gradel.workers.max=2
kotlin.incremental=true
android.useAndroidX=true
android.enableJetifier=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
